-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('create_room_pb')


local CTSCREATEROOM = protobuf.Descriptor();
local CTSCREATEROOM_USERID_FIELD = protobuf.FieldDescriptor();
local STCCREATEROOM = protobuf.Descriptor();
local STCCREATEROOM_USERID_FIELD = protobuf.FieldDescriptor();
local STCCREATEROOM_ROOMID_FIELD = protobuf.FieldDescriptor();

CTSCREATEROOM_USERID_FIELD.name = "userId"
CTSCREATEROOM_USERID_FIELD.full_name = ".pb.CtsCreateRoom.userId"
CTSCREATEROOM_USERID_FIELD.number = 1
CTSCREATEROOM_USERID_FIELD.index = 0
CTSCREATEROOM_USERID_FIELD.label = 1
CTSCREATEROOM_USERID_FIELD.has_default_value = false
CTSCREATEROOM_USERID_FIELD.default_value = 0
CTSCREATEROOM_USERID_FIELD.type = 3
CTSCREATEROOM_USERID_FIELD.cpp_type = 2

CTSCREATEROOM.name = "CtsCreateRoom"
CTSCREATEROOM.full_name = ".pb.CtsCreateRoom"
CTSCREATEROOM.nested_types = {}
CTSCREATEROOM.enum_types = {}
CTSCREATEROOM.fields = {CTSCREATEROOM_USERID_FIELD}
CTSCREATEROOM.is_extendable = false
CTSCREATEROOM.extensions = {}
STCCREATEROOM_USERID_FIELD.name = "userId"
STCCREATEROOM_USERID_FIELD.full_name = ".pb.StcCreateRoom.userId"
STCCREATEROOM_USERID_FIELD.number = 1
STCCREATEROOM_USERID_FIELD.index = 0
STCCREATEROOM_USERID_FIELD.label = 1
STCCREATEROOM_USERID_FIELD.has_default_value = false
STCCREATEROOM_USERID_FIELD.default_value = 0
STCCREATEROOM_USERID_FIELD.type = 3
STCCREATEROOM_USERID_FIELD.cpp_type = 2

STCCREATEROOM_ROOMID_FIELD.name = "roomId"
STCCREATEROOM_ROOMID_FIELD.full_name = ".pb.StcCreateRoom.roomId"
STCCREATEROOM_ROOMID_FIELD.number = 3
STCCREATEROOM_ROOMID_FIELD.index = 1
STCCREATEROOM_ROOMID_FIELD.label = 1
STCCREATEROOM_ROOMID_FIELD.has_default_value = false
STCCREATEROOM_ROOMID_FIELD.default_value = 0
STCCREATEROOM_ROOMID_FIELD.type = 3
STCCREATEROOM_ROOMID_FIELD.cpp_type = 2

STCCREATEROOM.name = "StcCreateRoom"
STCCREATEROOM.full_name = ".pb.StcCreateRoom"
STCCREATEROOM.nested_types = {}
STCCREATEROOM.enum_types = {}
STCCREATEROOM.fields = {STCCREATEROOM_USERID_FIELD, STCCREATEROOM_ROOMID_FIELD}
STCCREATEROOM.is_extendable = false
STCCREATEROOM.extensions = {}

CtsCreateRoom = protobuf.Message(CTSCREATEROOM)
StcCreateRoom = protobuf.Message(STCCREATEROOM)

