-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('error_notice_pb')


local STCERRORNOTICE = protobuf.Descriptor();
local STCERRORNOTICE_ID_FIELD = protobuf.FieldDescriptor();
local STCERRORNOTICE_INFO_FIELD = protobuf.FieldDescriptor();

STCERRORNOTICE_ID_FIELD.name = "Id"
STCERRORNOTICE_ID_FIELD.full_name = ".pb.StcErrorNotice.Id"
STCERRORNOTICE_ID_FIELD.number = 1
STCERRORNOTICE_ID_FIELD.index = 0
STCERRORNOTICE_ID_FIELD.label = 1
STCERRORNOTICE_ID_FIELD.has_default_value = false
STCERRORNOTICE_ID_FIELD.default_value = 0
STCERRORNOTICE_ID_FIELD.type = 5
STCERRORNOTICE_ID_FIELD.cpp_type = 1

STCERRORNOTICE_INFO_FIELD.name = "info"
STCERRORNOTICE_INFO_FIELD.full_name = ".pb.StcErrorNotice.info"
STCERRORNOTICE_INFO_FIELD.number = 2
STCERRORNOTICE_INFO_FIELD.index = 1
STCERRORNOTICE_INFO_FIELD.label = 1
STCERRORNOTICE_INFO_FIELD.has_default_value = false
STCERRORNOTICE_INFO_FIELD.default_value = ""
STCERRORNOTICE_INFO_FIELD.type = 9
STCERRORNOTICE_INFO_FIELD.cpp_type = 9

STCERRORNOTICE.name = "StcErrorNotice"
STCERRORNOTICE.full_name = ".pb.StcErrorNotice"
STCERRORNOTICE.nested_types = {}
STCERRORNOTICE.enum_types = {}
STCERRORNOTICE.fields = {STCERRORNOTICE_ID_FIELD, STCERRORNOTICE_INFO_FIELD}
STCERRORNOTICE.is_extendable = false
STCERRORNOTICE.extensions = {}

StcErrorNotice = protobuf.Message(STCERRORNOTICE)

