-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('message_pb')


local HEADER = protobuf.Descriptor();
local HEADER_ID_FIELD = protobuf.FieldDescriptor();
local HEADER_USERID_FIELD = protobuf.FieldDescriptor();
local HEADER_SESSIONID_FIELD = protobuf.FieldDescriptor();
local HEADER_SERVICEID0_FIELD = protobuf.FieldDescriptor();
local HEADER_SERVICEID1_FIELD = protobuf.FieldDescriptor();
local HEADER_TOKEN_FIELD = protobuf.FieldDescriptor();
local HEADER_TOKENEXPIREDTIME_FIELD = protobuf.FieldDescriptor();
local MESSAGE = protobuf.Descriptor();
local MESSAGE_HEADER_FIELD = protobuf.FieldDescriptor();
local MESSAGE_BODY_FIELD = protobuf.FieldDescriptor();

HEADER_ID_FIELD.name = "id"
HEADER_ID_FIELD.full_name = ".pb.Header.id"
HEADER_ID_FIELD.number = 1
HEADER_ID_FIELD.index = 0
HEADER_ID_FIELD.label = 1
HEADER_ID_FIELD.has_default_value = false
HEADER_ID_FIELD.default_value = 0
HEADER_ID_FIELD.type = 5
HEADER_ID_FIELD.cpp_type = 1

HEADER_USERID_FIELD.name = "userId"
HEADER_USERID_FIELD.full_name = ".pb.Header.userId"
HEADER_USERID_FIELD.number = 2
HEADER_USERID_FIELD.index = 1
HEADER_USERID_FIELD.label = 1
HEADER_USERID_FIELD.has_default_value = false
HEADER_USERID_FIELD.default_value = 0
HEADER_USERID_FIELD.type = 3
HEADER_USERID_FIELD.cpp_type = 2

HEADER_SESSIONID_FIELD.name = "sessionId"
HEADER_SESSIONID_FIELD.full_name = ".pb.Header.sessionId"
HEADER_SESSIONID_FIELD.number = 3
HEADER_SESSIONID_FIELD.index = 2
HEADER_SESSIONID_FIELD.label = 1
HEADER_SESSIONID_FIELD.has_default_value = false
HEADER_SESSIONID_FIELD.default_value = 0
HEADER_SESSIONID_FIELD.type = 3
HEADER_SESSIONID_FIELD.cpp_type = 2

HEADER_SERVICEID0_FIELD.name = "serviceId0"
HEADER_SERVICEID0_FIELD.full_name = ".pb.Header.serviceId0"
HEADER_SERVICEID0_FIELD.number = 4
HEADER_SERVICEID0_FIELD.index = 3
HEADER_SERVICEID0_FIELD.label = 1
HEADER_SERVICEID0_FIELD.has_default_value = false
HEADER_SERVICEID0_FIELD.default_value = 0
HEADER_SERVICEID0_FIELD.type = 5
HEADER_SERVICEID0_FIELD.cpp_type = 1

HEADER_SERVICEID1_FIELD.name = "serviceId1"
HEADER_SERVICEID1_FIELD.full_name = ".pb.Header.serviceId1"
HEADER_SERVICEID1_FIELD.number = 5
HEADER_SERVICEID1_FIELD.index = 4
HEADER_SERVICEID1_FIELD.label = 1
HEADER_SERVICEID1_FIELD.has_default_value = false
HEADER_SERVICEID1_FIELD.default_value = 0
HEADER_SERVICEID1_FIELD.type = 5
HEADER_SERVICEID1_FIELD.cpp_type = 1

HEADER_TOKEN_FIELD.name = "token"
HEADER_TOKEN_FIELD.full_name = ".pb.Header.token"
HEADER_TOKEN_FIELD.number = 6
HEADER_TOKEN_FIELD.index = 5
HEADER_TOKEN_FIELD.label = 1
HEADER_TOKEN_FIELD.has_default_value = false
HEADER_TOKEN_FIELD.default_value = ""
HEADER_TOKEN_FIELD.type = 9
HEADER_TOKEN_FIELD.cpp_type = 9

HEADER_TOKENEXPIREDTIME_FIELD.name = "tokenExpiredTime"
HEADER_TOKENEXPIREDTIME_FIELD.full_name = ".pb.Header.tokenExpiredTime"
HEADER_TOKENEXPIREDTIME_FIELD.number = 7
HEADER_TOKENEXPIREDTIME_FIELD.index = 6
HEADER_TOKENEXPIREDTIME_FIELD.label = 1
HEADER_TOKENEXPIREDTIME_FIELD.has_default_value = false
HEADER_TOKENEXPIREDTIME_FIELD.default_value = 0
HEADER_TOKENEXPIREDTIME_FIELD.type = 3
HEADER_TOKENEXPIREDTIME_FIELD.cpp_type = 2

HEADER.name = "Header"
HEADER.full_name = ".pb.Header"
HEADER.nested_types = {}
HEADER.enum_types = {}
HEADER.fields = {HEADER_ID_FIELD, HEADER_USERID_FIELD, HEADER_SESSIONID_FIELD, HEADER_SERVICEID0_FIELD, HEADER_SERVICEID1_FIELD, HEADER_TOKEN_FIELD, HEADER_TOKENEXPIREDTIME_FIELD}
HEADER.is_extendable = false
HEADER.extensions = {}
MESSAGE_HEADER_FIELD.name = "header"
MESSAGE_HEADER_FIELD.full_name = ".pb.Message.header"
MESSAGE_HEADER_FIELD.number = 1
MESSAGE_HEADER_FIELD.index = 0
MESSAGE_HEADER_FIELD.label = 1
MESSAGE_HEADER_FIELD.has_default_value = false
MESSAGE_HEADER_FIELD.default_value = nil
MESSAGE_HEADER_FIELD.message_type = HEADER
MESSAGE_HEADER_FIELD.type = 11
MESSAGE_HEADER_FIELD.cpp_type = 10

MESSAGE_BODY_FIELD.name = "body"
MESSAGE_BODY_FIELD.full_name = ".pb.Message.body"
MESSAGE_BODY_FIELD.number = 2
MESSAGE_BODY_FIELD.index = 1
MESSAGE_BODY_FIELD.label = 1
MESSAGE_BODY_FIELD.has_default_value = false
MESSAGE_BODY_FIELD.default_value = ""
MESSAGE_BODY_FIELD.type = 12
MESSAGE_BODY_FIELD.cpp_type = 9

MESSAGE.name = "Message"
MESSAGE.full_name = ".pb.Message"
MESSAGE.nested_types = {}
MESSAGE.enum_types = {}
MESSAGE.fields = {MESSAGE_HEADER_FIELD, MESSAGE_BODY_FIELD}
MESSAGE.is_extendable = false
MESSAGE.extensions = {}

Header = protobuf.Message(HEADER)
Message = protobuf.Message(MESSAGE)

