-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('play_piece_pb')


local CTSPLAYPIECE = protobuf.Descriptor();
local CTSPLAYPIECE_ROOMID_FIELD = protobuf.FieldDescriptor();
local CTSPLAYPIECE_CHAIRID_FIELD = protobuf.FieldDescriptor();
local CTSPLAYPIECE_X_FIELD = protobuf.FieldDescriptor();
local CTSPLAYPIECE_Y_FIELD = protobuf.FieldDescriptor();
local STCPLAYPIECE = protobuf.Descriptor();
local STCPLAYPIECE_ROOMID_FIELD = protobuf.FieldDescriptor();
local STCPLAYPIECE_CHAIRID_FIELD = protobuf.FieldDescriptor();
local STCPLAYPIECE_X_FIELD = protobuf.FieldDescriptor();
local STCPLAYPIECE_Y_FIELD = protobuf.FieldDescriptor();
local STCGAMERESULT = protobuf.Descriptor();
local STCGAMERESULT_WINNER_FIELD = protobuf.FieldDescriptor();
local STCGAMERESULT_LOOSER_FIELD = protobuf.FieldDescriptor();
local STCGAMERESULT_PIECELIST_FIELD = protobuf.FieldDescriptor();
local PIECE = protobuf.Descriptor();
local PIECE_VALUE_FIELD = protobuf.FieldDescriptor();
local PIECE_X_FIELD = protobuf.FieldDescriptor();
local PIECE_Y_FIELD = protobuf.FieldDescriptor();

CTSPLAYPIECE_ROOMID_FIELD.name = "roomId"
CTSPLAYPIECE_ROOMID_FIELD.full_name = ".pb.CtsPlayPiece.roomId"
CTSPLAYPIECE_ROOMID_FIELD.number = 1
CTSPLAYPIECE_ROOMID_FIELD.index = 0
CTSPLAYPIECE_ROOMID_FIELD.label = 1
CTSPLAYPIECE_ROOMID_FIELD.has_default_value = false
CTSPLAYPIECE_ROOMID_FIELD.default_value = 0
CTSPLAYPIECE_ROOMID_FIELD.type = 3
CTSPLAYPIECE_ROOMID_FIELD.cpp_type = 2

CTSPLAYPIECE_CHAIRID_FIELD.name = "chairId"
CTSPLAYPIECE_CHAIRID_FIELD.full_name = ".pb.CtsPlayPiece.chairId"
CTSPLAYPIECE_CHAIRID_FIELD.number = 2
CTSPLAYPIECE_CHAIRID_FIELD.index = 1
CTSPLAYPIECE_CHAIRID_FIELD.label = 1
CTSPLAYPIECE_CHAIRID_FIELD.has_default_value = false
CTSPLAYPIECE_CHAIRID_FIELD.default_value = 0
CTSPLAYPIECE_CHAIRID_FIELD.type = 5
CTSPLAYPIECE_CHAIRID_FIELD.cpp_type = 1

CTSPLAYPIECE_X_FIELD.name = "x"
CTSPLAYPIECE_X_FIELD.full_name = ".pb.CtsPlayPiece.x"
CTSPLAYPIECE_X_FIELD.number = 3
CTSPLAYPIECE_X_FIELD.index = 2
CTSPLAYPIECE_X_FIELD.label = 1
CTSPLAYPIECE_X_FIELD.has_default_value = false
CTSPLAYPIECE_X_FIELD.default_value = 0
CTSPLAYPIECE_X_FIELD.type = 5
CTSPLAYPIECE_X_FIELD.cpp_type = 1

CTSPLAYPIECE_Y_FIELD.name = "y"
CTSPLAYPIECE_Y_FIELD.full_name = ".pb.CtsPlayPiece.y"
CTSPLAYPIECE_Y_FIELD.number = 4
CTSPLAYPIECE_Y_FIELD.index = 3
CTSPLAYPIECE_Y_FIELD.label = 1
CTSPLAYPIECE_Y_FIELD.has_default_value = false
CTSPLAYPIECE_Y_FIELD.default_value = 0
CTSPLAYPIECE_Y_FIELD.type = 5
CTSPLAYPIECE_Y_FIELD.cpp_type = 1

CTSPLAYPIECE.name = "CtsPlayPiece"
CTSPLAYPIECE.full_name = ".pb.CtsPlayPiece"
CTSPLAYPIECE.nested_types = {}
CTSPLAYPIECE.enum_types = {}
CTSPLAYPIECE.fields = {CTSPLAYPIECE_ROOMID_FIELD, CTSPLAYPIECE_CHAIRID_FIELD, CTSPLAYPIECE_X_FIELD, CTSPLAYPIECE_Y_FIELD}
CTSPLAYPIECE.is_extendable = false
CTSPLAYPIECE.extensions = {}
STCPLAYPIECE_ROOMID_FIELD.name = "roomId"
STCPLAYPIECE_ROOMID_FIELD.full_name = ".pb.StcPlayPiece.roomId"
STCPLAYPIECE_ROOMID_FIELD.number = 1
STCPLAYPIECE_ROOMID_FIELD.index = 0
STCPLAYPIECE_ROOMID_FIELD.label = 1
STCPLAYPIECE_ROOMID_FIELD.has_default_value = false
STCPLAYPIECE_ROOMID_FIELD.default_value = 0
STCPLAYPIECE_ROOMID_FIELD.type = 3
STCPLAYPIECE_ROOMID_FIELD.cpp_type = 2

STCPLAYPIECE_CHAIRID_FIELD.name = "chairId"
STCPLAYPIECE_CHAIRID_FIELD.full_name = ".pb.StcPlayPiece.chairId"
STCPLAYPIECE_CHAIRID_FIELD.number = 2
STCPLAYPIECE_CHAIRID_FIELD.index = 1
STCPLAYPIECE_CHAIRID_FIELD.label = 1
STCPLAYPIECE_CHAIRID_FIELD.has_default_value = false
STCPLAYPIECE_CHAIRID_FIELD.default_value = 0
STCPLAYPIECE_CHAIRID_FIELD.type = 5
STCPLAYPIECE_CHAIRID_FIELD.cpp_type = 1

STCPLAYPIECE_X_FIELD.name = "x"
STCPLAYPIECE_X_FIELD.full_name = ".pb.StcPlayPiece.x"
STCPLAYPIECE_X_FIELD.number = 3
STCPLAYPIECE_X_FIELD.index = 2
STCPLAYPIECE_X_FIELD.label = 1
STCPLAYPIECE_X_FIELD.has_default_value = false
STCPLAYPIECE_X_FIELD.default_value = 0
STCPLAYPIECE_X_FIELD.type = 5
STCPLAYPIECE_X_FIELD.cpp_type = 1

STCPLAYPIECE_Y_FIELD.name = "y"
STCPLAYPIECE_Y_FIELD.full_name = ".pb.StcPlayPiece.y"
STCPLAYPIECE_Y_FIELD.number = 4
STCPLAYPIECE_Y_FIELD.index = 3
STCPLAYPIECE_Y_FIELD.label = 1
STCPLAYPIECE_Y_FIELD.has_default_value = false
STCPLAYPIECE_Y_FIELD.default_value = 0
STCPLAYPIECE_Y_FIELD.type = 5
STCPLAYPIECE_Y_FIELD.cpp_type = 1

STCPLAYPIECE.name = "StcPlayPiece"
STCPLAYPIECE.full_name = ".pb.StcPlayPiece"
STCPLAYPIECE.nested_types = {}
STCPLAYPIECE.enum_types = {}
STCPLAYPIECE.fields = {STCPLAYPIECE_ROOMID_FIELD, STCPLAYPIECE_CHAIRID_FIELD, STCPLAYPIECE_X_FIELD, STCPLAYPIECE_Y_FIELD}
STCPLAYPIECE.is_extendable = false
STCPLAYPIECE.extensions = {}
STCGAMERESULT_WINNER_FIELD.name = "winner"
STCGAMERESULT_WINNER_FIELD.full_name = ".pb.StcGameResult.winner"
STCGAMERESULT_WINNER_FIELD.number = 1
STCGAMERESULT_WINNER_FIELD.index = 0
STCGAMERESULT_WINNER_FIELD.label = 1
STCGAMERESULT_WINNER_FIELD.has_default_value = false
STCGAMERESULT_WINNER_FIELD.default_value = 0
STCGAMERESULT_WINNER_FIELD.type = 5
STCGAMERESULT_WINNER_FIELD.cpp_type = 1

STCGAMERESULT_LOOSER_FIELD.name = "looser"
STCGAMERESULT_LOOSER_FIELD.full_name = ".pb.StcGameResult.looser"
STCGAMERESULT_LOOSER_FIELD.number = 2
STCGAMERESULT_LOOSER_FIELD.index = 1
STCGAMERESULT_LOOSER_FIELD.label = 1
STCGAMERESULT_LOOSER_FIELD.has_default_value = false
STCGAMERESULT_LOOSER_FIELD.default_value = 0
STCGAMERESULT_LOOSER_FIELD.type = 5
STCGAMERESULT_LOOSER_FIELD.cpp_type = 1

STCGAMERESULT_PIECELIST_FIELD.name = "pieceList"
STCGAMERESULT_PIECELIST_FIELD.full_name = ".pb.StcGameResult.pieceList"
STCGAMERESULT_PIECELIST_FIELD.number = 3
STCGAMERESULT_PIECELIST_FIELD.index = 2
STCGAMERESULT_PIECELIST_FIELD.label = 3
STCGAMERESULT_PIECELIST_FIELD.has_default_value = false
STCGAMERESULT_PIECELIST_FIELD.default_value = {}
STCGAMERESULT_PIECELIST_FIELD.message_type = _PIECE
STCGAMERESULT_PIECELIST_FIELD.type = 11
STCGAMERESULT_PIECELIST_FIELD.cpp_type = 10

STCGAMERESULT.name = "StcGameResult"
STCGAMERESULT.full_name = ".pb.StcGameResult"
STCGAMERESULT.nested_types = {}
STCGAMERESULT.enum_types = {}
STCGAMERESULT.fields = {STCGAMERESULT_WINNER_FIELD, STCGAMERESULT_LOOSER_FIELD, STCGAMERESULT_PIECELIST_FIELD}
STCGAMERESULT.is_extendable = false
STCGAMERESULT.extensions = {}
PIECE_VALUE_FIELD.name = "value"
PIECE_VALUE_FIELD.full_name = ".pb.Piece.value"
PIECE_VALUE_FIELD.number = 1
PIECE_VALUE_FIELD.index = 0
PIECE_VALUE_FIELD.label = 1
PIECE_VALUE_FIELD.has_default_value = false
PIECE_VALUE_FIELD.default_value = 0
PIECE_VALUE_FIELD.type = 5
PIECE_VALUE_FIELD.cpp_type = 1

PIECE_X_FIELD.name = "x"
PIECE_X_FIELD.full_name = ".pb.Piece.x"
PIECE_X_FIELD.number = 2
PIECE_X_FIELD.index = 1
PIECE_X_FIELD.label = 1
PIECE_X_FIELD.has_default_value = false
PIECE_X_FIELD.default_value = 0
PIECE_X_FIELD.type = 5
PIECE_X_FIELD.cpp_type = 1

PIECE_Y_FIELD.name = "y"
PIECE_Y_FIELD.full_name = ".pb.Piece.y"
PIECE_Y_FIELD.number = 3
PIECE_Y_FIELD.index = 2
PIECE_Y_FIELD.label = 1
PIECE_Y_FIELD.has_default_value = false
PIECE_Y_FIELD.default_value = 0
PIECE_Y_FIELD.type = 5
PIECE_Y_FIELD.cpp_type = 1

PIECE.name = "Piece"
PIECE.full_name = ".pb.Piece"
PIECE.nested_types = {}
PIECE.enum_types = {}
PIECE.fields = {PIECE_VALUE_FIELD, PIECE_X_FIELD, PIECE_Y_FIELD}
PIECE.is_extendable = false
PIECE.extensions = {}

CtsPlayPiece = protobuf.Message(CTSPLAYPIECE)
Piece = protobuf.Message(PIECE)
StcGameResult = protobuf.Message(STCGAMERESULT)
StcPlayPiece = protobuf.Message(STCPLAYPIECE)

