-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('service_pb')


local SERVICE = protobuf.EnumDescriptor();
local SERVICE_NULL_ENUM = protobuf.EnumValueDescriptor();
local SERVICE_DB_ENUM = protobuf.EnumValueDescriptor();
local SERVICE_LOGIN_ENUM = protobuf.EnumValueDescriptor();
local SERVICE_G001_ENUM = protobuf.EnumValueDescriptor();
local SERVICE_GW_ENUM = protobuf.EnumValueDescriptor();

SERVICE_NULL_ENUM.name = "NULL"
SERVICE_NULL_ENUM.index = 0
SERVICE_NULL_ENUM.number = 0
SERVICE_DB_ENUM.name = "DB"
SERVICE_DB_ENUM.index = 1
SERVICE_DB_ENUM.number = 1
SERVICE_LOGIN_ENUM.name = "LOGIN"
SERVICE_LOGIN_ENUM.index = 2
SERVICE_LOGIN_ENUM.number = 2
SERVICE_G001_ENUM.name = "G001"
SERVICE_G001_ENUM.index = 3
SERVICE_G001_ENUM.number = 3
SERVICE_GW_ENUM.name = "GW"
SERVICE_GW_ENUM.index = 4
SERVICE_GW_ENUM.number = 4
SERVICE.name = "SERVICE"
SERVICE.full_name = ".pb.SERVICE"
SERVICE.values = {SERVICE_NULL_ENUM,SERVICE_DB_ENUM,SERVICE_LOGIN_ENUM,SERVICE_G001_ENUM,SERVICE_GW_ENUM}

DB = 1
G001 = 3
GW = 4
LOGIN = 2
NULL = 0

