// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgJwYio4CgdTRVJWSUNFEggKBE5VTEwQABIGCgJE",
            "QhABEgkKBUxPR0lOEAISCAoERzAwMRADEgYKAkdXEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.SERVICE), }, null));
    }
    #endregion

  }
  #region Enums
  public enum SERVICE {
    [pbr::OriginalName("NULL")] Null = 0,
    [pbr::OriginalName("DB")] Db = 1,
    [pbr::OriginalName("LOGIN")] Login = 2,
    [pbr::OriginalName("G001")] G001 = 3,
    [pbr::OriginalName("GW")] Gw = 4,
  }

  #endregion

}

#endregion Designer generated code
